version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gomod-minor-patch:
        update-types:
          - "minor"
          - "patch"
      gomod-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      docker-minor-patch:
        update-types:
          - "minor"
          - "patch" 
      docker-major:
        update-types:
          - "major"
